package com.example.offred.di

import android.content.Context

import com.example.offred.*
import com.example.offred.Room.FavoritesDAO
import com.example.offred.Room.T3DAO
import com.example.offred.Room.T5DAO
import com.example.offred.models.More
import com.example.offred.models.T1
import com.example.offred.models.T3
import com.example.offred.models.T5
import com.example.offred.models.Thing
import com.example.offred.repos.BaseFavoritesRepo
import com.example.offred.moshiadapters.DescriptionAdapter
import com.example.offred.moshiadapters.MediaList

import com.example.offred.moshiadapters.RedditPostAdapter
import com.example.offred.repos.BaseSubredditsAndPostsRepo
import com.example.offred.repos.FavoritesRepo
import com.example.offred.repos.SubredditsAndPostsRepo
import com.google.android.exoplayer2.ExoPlayer
import com.squareup.moshi.Moshi
import com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.adapter.rxjava3.RxJava3CallAdapterFactory
import retrofit2.converter.moshi.MoshiConverterFactory
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
class SessionModule {
    @Singleton
    @Provides
    fun provideSharedPreference(@ApplicationContext context: Context): SessionManager {
        return SessionManager(context)
    }
}

@InstallIn(SingletonComponent::class)
@Module
object RedditModule {
    private const val BASE_URL="https://oauth.reddit.com/"

    @Singleton
    @Provides
    fun provideAPICallInterface(retrofit: Retrofit): API =
        retrofit.create(API::class.java)


    @Singleton
    @Provides
    fun provideLoginInterface(retrofit: Retrofit): AuthAPI =
        retrofit.create(AuthAPI::class.java)

    @Singleton
    @Provides
    fun provideRetrofit(okHttpClient: OkHttpClient, mosh: Moshi): Retrofit =
        Retrofit.Builder()
                .client(okHttpClient)
                .addConverterFactory(MoshiConverterFactory.create(mosh))
                .addCallAdapterFactory(RxJava3CallAdapterFactory.create())
                .baseUrl(BASE_URL)
                .build()

    @Singleton
    @Provides
    fun provideOkHttpClient(httpLoggingInterceptor: HttpLoggingInterceptor,
                            redirect: RedirectInterceptor,auth:AuthInterceptor):OkHttpClient =

            OkHttpClient.Builder()
                        .followRedirects(false)
                        .followSslRedirects(false)
                        .addInterceptor(redirect)
                        .addInterceptor(auth)
                        .addInterceptor(httpLoggingInterceptor)
                        .build()

    @Singleton
    @Provides
    fun provideHttpLoggingInterceptor() =
        HttpLoggingInterceptor().apply { level = HttpLoggingInterceptor.Level.HEADERS }

    @Singleton
    @Provides
    fun provideRedirectInterceptor() = RedirectInterceptor()

    @Singleton
    @Provides
    fun provideAuthInterceptor(sm:SessionManager) = AuthInterceptor(sm)

    @Singleton
    @Provides
    fun provideMoshi(): Moshi = Moshi.Builder()

        .add(
            // This is the magic adapter that replaces your old ones.
            PolymorphicJsonAdapterFactory.of(Thing::class.java, "kind")
                .withSubtype(T1::class.java, "t1")
                .withSubtype(T3::class.java, "t3")
                .withSubtype(T5::class.java, "t5")
                .withSubtype(More::class.java, "more")
        )
        .add(DescriptionAdapter())
        .add(MediaList())
        .add(KotlinJsonAdapterFactory()) //fallback, maybe remove as they are autogenerated
        .build()
}


@InstallIn(SingletonComponent::class)
@Module
object ExoPlayerModule {
    @Singleton
    @Provides
    fun provideExoplayer(@ApplicationContext ctx: Context): ExoPlayer =
        ExoPlayer.Builder(ctx).build()
}

@InstallIn(SingletonComponent::class)
@Module
object RepoModule {
    @Singleton
    @Provides
    fun providePostsRepository(t5Dao: T5DAO, t3Dao: T3DAO,api: API ):
            BaseSubredditsAndPostsRepo = SubredditsAndPostsRepo( t5Dao, t3Dao,api)
    @Singleton
    @Provides
    fun provideFavoritesRepository(t5Dao: T5DAO, t3Dao: T3DAO, favs: FavoritesDAO, api:API)
            : BaseFavoritesRepo = FavoritesRepo(t5Dao, t3Dao,favs, api)
}
