package com.example.renewed.DefaultDBContents

import com.example.renewed.models.RoomT5
import java.time.Instant

val t5SampleList = listOf(
    RoomT5(
        name = "t5_tu4j3",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 88),
    RoomT5(
        name = "t5_tuhj3",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 12)
,
RoomT5(
name = "t5_t88jk",
displayName = "Funwithroses",
description ="A great site",
thumbnail ="",
banner_img ="",
created_utc = Instant.now(),
timeLastAccessed = Instant.now(),
subscribers = 8,
isSaved = false,
totalViews = 1),

    RoomT5(
        name = "t5_ojj3",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_tyuj3",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 10000)
    ,
    RoomT5(
        name = "t5_t880k",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 88),

    RoomT5(
        name = "t5_nu896",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 60),
    RoomT5(
        name = "t5_t9i9i",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 340)
    ,
    RoomT5(
        name = "t5_tiikk",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 900),

    RoomT5(
        name = "t5_oppoi",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_ty993",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_yu80k",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_t9993",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_okjmj3",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_t88012",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_odeum",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_typppo",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_tgggg0k",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_poi896",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_lli9i",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_fiikk",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_p0oi",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_tpp93",
        displayName = "Funwithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_ool80k",
        displayName = "Funwithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)






)

