package com.example.renewed.DefaultDBContents

import com.example.renewed.models.RoomT5
import java.time.Instant

val t5SampleList = listOf(
    RoomT5(
        name = "t5_tu4j3",
        displayName = "Funwithradsasdoses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 88),
    RoomT5(
        name = "t5_t7yh",
        displayName = "aaaa",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 12)
,
RoomT5(
name = "t5_t88jk",
displayName = "Funwa",
description ="A great site",
thumbnail ="",
banner_img ="",
created_utc = Instant.now(),
timeLastAccessed = Instant.now(),
subscribers = 8,
isSaved = false,
totalViews = 1),

    RoomT5(
        name = "t5_ojj3",
        displayName = "Faaaaaaaaaaaroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_tyuj3",
        displayName = "A good one",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 10000)
    ,
    RoomT5(
        name = "t5_t880k",
        displayName = "Fsgdsgsoses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 88),

    RoomT5(
        name = "t5_nu896",
        displayName = "tttasghs",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 60),
    RoomT5(
        name = "t5_tuhj3",
        displayName = "Fttttttttttses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 340)
    ,
    RoomT5(
        name = "t5_tiikk",
        displayName = "Fafefefroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 900),

    RoomT5(
        name = "t5_oppoi",
        displayName = "FuDeeeeDDDDDDDD",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_ty993",
        displayName = "FunDDDDDDDDDes",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_yu80k",
        displayName = "Faaaaaaaithroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_t9993",
        displayName = "Fksfroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_okjmj3",
        displayName = "aaaaithses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_t88012",
        displayName = "Fun1oses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_odeum",
        displayName = "Funwddasses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_typppo",
        displayName = "Funwi2222",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_tgggg0k",
        displayName = "Funwitffefes",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_poi896",
        displayName = "Funaaahroses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_lli9i",
        displayName = "Faaaits",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_fiikk",
        displayName = "Fueeses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),

    RoomT5(
        name = "t5_p0oi",
        displayName = "eeeeeeeeeoses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0),
    RoomT5(
        name = "t5_tpp93",
        displayName = "Funwiaaaes",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)
    ,
    RoomT5(
        name = "t5_ool80k",
        displayName = "Funwiffaoses",
        description ="A great site",
        thumbnail ="",
        banner_img ="",
        created_utc = Instant.now(),
        timeLastAccessed = Instant.now(),
        subscribers = 8,
        isSaved = false,
        totalViews = 0)

)

